config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  constraints(Subdomain.new) do
    match '/', to: 'site#home', via: [:get]
    get '/about', to: 'site#about'
    get '/news', to: 'site#news'
    get '/gallery', to: 'site#gallery'
    get '/events', to: 'site#events'
    get '/contact', to: 'site#contact'
    get '/gallery/:album_id', to: 'site#photo_albums', as: 'photo_albums'
    get '/terms_and_condition', to: 'site#terms_condition'
    get '/privacy_policy', to: 'site#privacy_policy'
  end

  resources :pages, except: %i[new edit]
  resources :fb_page, only: [:index] do
    resources :subscription, only: %i[new create]
    delete '/subscription/cancel', to: 'subscription#cancel_subscription', as: 'cancel_subscription'
    put 'sync', to: 'fb_page#sync', as: 'sync'
    get '/billing', to: 'billing#billing_history', as: 'billing_history'
  end
  mount StripeEvent::Engine, at: '/subscription/stripe/webhook'
  resources :fb_page_template, only: %i[show update]
  resources :billing, only: [:index]
  resources :dashboard, only: [:index]

  scope :editor do
    get 'design/:fb_page_id', to: 'editor#design', as: 'editor_design'
    get 'template/pages/:fb_page_id', to: 'editor#list_pages'
    put 'page/:fb_page_id', to: 'editor#page'
    post 'setting/:fb_page_id', to: 'editor#create_setting', as: 'editor_create_setting'
    get ':fb_page_id/setting/:fb_page_template_id', to: 'editor#show_setting', as: 'editor_show_setting'
  end

  scope :site do
    get ':fb_page_id/home', to: 'site#home', as: 'site_home'
    get ':fb_page_id/about', to: 'site#about', as: 'site_about'
    get ':fb_page_id/contact', to: 'site#contact', as: 'site_contact'
    post ':fb_page_id/contact', to: 'site#send_contact_message', as: 'site_contact_post'
    get ':fb_page_id/events', to: 'site#events', as: 'site_events'
    get ':fb_page_id/gallery', to: 'site#gallery', as: 'site_gallery'
    get ':fb_page_id/gallery/:album_id', to: 'site#photo_albums', as: 'site_photo_albums'
    get ':fb_page_id/privacy_policy', to: 'site#privacy_policy', as: 'site_privacy_policy'
    get ':fb_page_id/terms_condition', to: 'site#terms_condition', as: 'site_terms_condition'
    get ':fb_page_id/news', to: 'site#news', as: 'site_news'
  end

  put '/:fb_page_id/templates/:id/properties', to: 'templates#properties', as: 'properties'
  get '/:fb_page_id/templates', to: 'templates#index', as: 'templates'
  post '/:fb_page_id/templates/:template_id', to: 'templates#choose', as: 'choose_template'

  root to: 'home#index'
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @pages = DashboardDecorator.decorate_collection(current_user.fb_pages.order('fb_pages.status ASC, fb_pages.updated_at DESC'))
  end
end

app/views/dashboard/index.slim
- content_for :title do
  |  Fuitter | Dashboard

= render 'shared/dashboard/navbar'
.grid-flex style= "display:flex;position:fixed;width:100vw;"
  .is-hidden-mobile.sidebar-modi
    = render 'shared/dashboard/sidebar'
  .is-mobile.main-contain-area
    .is-centered.main-content-area.thead.is-mobile
      .is-mobile.name
        | your facebook pages
    - @pages.each do |page|
      .is-mobile.dash-data
        .is-mobile.data-logo
          img src=(page.picture)
        .is-mobile.text
          = page.name
        .status-show
          - if page.status
            .notch-active class=(page.state[page.status][:type])
              i.fa.fa-globe
                = page.state[page.status][:value]
        - if page.status
          .is-mobile.condn
            = link_to 'View', site_home_path(page), target: '_blank', class: 'button conditional is-primary is-small'
            = link_to 'Edit', editor_design_path(page.id), class: 'button is-primary is-small'
        - else
          .is-mobile.condn-single
            = link_to 'Start', templates_path(page), class: 'button is-primary is-small'