config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  constraints(Subdomain.new) do
    match '/', to: 'site#home', via: [:get]
    get '/about', to: 'site#about'
    get '/news', to: 'site#news'
    get '/gallery', to: 'site#gallery'
    get '/events', to: 'site#events'
    get '/contact', to: 'site#contact'
    get '/gallery/:album_id', to: 'site#photo_albums', as: 'photo_albums'
    get '/terms_and_condition', to: 'site#terms_condition'
    get '/privacy_policy', to: 'site#privacy_policy'
  end

  resources :pages, except: %i[new edit]
  resources :fb_page, only: [:index] do
    resources :subscription, only: %i[new create]
    delete '/subscription/cancel', to: 'subscription#cancel_subscription', as: 'cancel_subscription'
    put 'sync', to: 'fb_page#sync', as: 'sync'
    get '/billing', to: 'billing#billing_history', as: 'billing_history'
  end
  mount StripeEvent::Engine, at: '/subscription/stripe/webhook'
  resources :fb_page_template, only: %i[show update]
  resources :billing, only: [:index]
  resources :dashboard, only: [:index]

  scope :editor do
    get 'design/:fb_page_id', to: 'editor#design', as: 'editor_design'
    get 'template/pages/:fb_page_id', to: 'editor#list_pages'
    put 'page/:fb_page_id', to: 'editor#page'
    post 'setting/:fb_page_id', to: 'editor#create_setting', as: 'editor_create_setting'
    get ':fb_page_id/setting/:fb_page_template_id', to: 'editor#show_setting', as: 'editor_show_setting'
  end

  scope :site do
    get ':fb_page_id/home', to: 'site#home', as: 'site_home'
    get ':fb_page_id/about', to: 'site#about', as: 'site_about'
    get ':fb_page_id/contact', to: 'site#contact', as: 'site_contact'
    post ':fb_page_id/contact', to: 'site#send_contact_message', as: 'site_contact_post'
    get ':fb_page_id/events', to: 'site#events', as: 'site_events'
    get ':fb_page_id/gallery', to: 'site#gallery', as: 'site_gallery'
    get ':fb_page_id/gallery/:album_id', to: 'site#photo_albums', as: 'site_photo_albums'
    get ':fb_page_id/privacy_policy', to: 'site#privacy_policy', as: 'site_privacy_policy'
    get ':fb_page_id/terms_condition', to: 'site#terms_condition', as: 'site_terms_condition'
    get ':fb_page_id/news', to: 'site#news', as: 'site_news'
  end

  put '/:fb_page_id/templates/:id/properties', to: 'templates#properties', as: 'properties'
  get '/:fb_page_id/templates', to: 'templates#index', as: 'templates'
  post '/:fb_page_id/templates/:template_id', to: 'templates#choose', as: 'choose_template'

  root to: 'home#index'
end

app/controllers/editor_controller.rb
# frozen_string_literal: true

class EditorController < ApplicationController
  TRIAL_PERIOD = 15

  before_action :authenticate_user!, :set_fb_page_template, :check_trial_period

  def design
    @fb_page_name = FbPage.find_by(id: @fb_page_id).name
    @default_template_value = @fb_page_template.template
    @pages = Page.list_pages(@fb_page_template)
  end

  def list_pages
    template = FbPageTemplate.find_by(fb_page_id: params[:fb_page_id])
    pages = Page.list_pages(template)
    render json: pages
  end

  def page
    # loop thru menu and set menu's parent id(ancestry) to nil in first loop
    # if menu have nested property then assign parent id for them
    page_param[:menu].each_with_index do |menu, index|
      parent = Page.find menu[:id]
      parent.update(position: index, parent: nil, display: menu['display'])
      next if menu[:nested].empty?

      menu[:nested].each_with_index do |sub_menu, index|
        page = Page.find sub_menu[:id]
        page.update!(position: index, parent: parent, display: sub_menu['display'])
      end
    end
  end

  def create_setting
    editor_setting = Setting.find_or_initialize_by(fb_page_template_id: params[:fb_page_template_id])
    editor_setting.attributes = setting_param
    editor_setting.save!
    render json: editor_setting
  end

  def show_setting
    editor_setting = Setting.find_by(fb_page_template_id: params[:fb_page_template_id])
    render json: editor_setting
  end

  private

  def page_param
    params.permit(menu: [:id, :title, :display, :position, :seo, :created_at, :updated_at, :fb_page_template_id, :uri, nested: %i[id title display position seo created_at updated_at fb_page_template_id uri]])
  end

  def setting_param
    params.require(:editor).permit(:domain, :subdomain, :fb_page_template_id, :fb_messenger, social_media: {}, legal_info: {})
  end

  def set_fb_page_template
    @fb_page_id = params[:fb_page_id]
    @fb_page_template = FbPageTemplate.find_by(fb_page_id: @fb_page_id)
  end

  def check_trial_period
    trial_exceeded =  Time.now.to_date > @fb_page_template.created_at.to_date + TRIAL_PERIOD
    if trial_exceeded && !@fb_page_template.subscribed?
      flash[:notice] = 'Your trial is over. Please upgrade to continue using it'
      redirect_to new_fb_page_subscription_url(@fb_page_id)
    end
  end
end

app/views/editor/design.html.slim
- content_for :title do
  |  Fuitter | Design

#editor
  <editor-nav :checkout="#{new_fb_page_subscription_url(@fb_page_id).to_json}" :sync="#{fb_page_sync_url(@fb_page_id).to_json}" :preview="#{site_home_url(@fb_page_id).to_json}" :url="#{dashboard_index_url.to_json}"></editor-nav>
  .main-window
    .main-sidebar
      <editor-sidebar :templates_url="#{templates_path(@fb_page_id).to_json}" :template="#{@fb_page_template.to_json}" :fb_page_id="#{@fb_page_id.to_json}" :pages="#{@pages.to_json}" :fb_page_name="#{@fb_page_name.to_json}" :default_template_value="#{@default_template_value.to_json}"></editor-sidebar>
    .main-iframe
      <preview :url="#{site_home_url(@fb_page_id).to_json}"></preview>
      <setting :template="#{@fb_page_template.to_json}" :fb_page_id="#{@fb_page_id.to_json}" :fb_page_name="#{@fb_page_name.to_json}"></setting>
= stylesheet_pack_tag 'editor'
= javascript_pack_tag 'editor'

app/views/editor/go_live.html.slim
section.section
  .columns.is-centered
    .column.is-6.border.pa5
      h1.title.is-3
        | Subscribe
      h1 Domain
      .columns
        .column.is-8
          input.input placeholder=("Domain name") type="text" /
        .column.is-4
          a.button.is-link Submit
      p
        | Choose a plan
        
        strong
          .columns
            .column.is-6
              .card.card-content
                .media
                  a
                    .media-content
                    p.title.is-4 Monthly
                    p.subtitle.is-6 $19 per month
                    .content
                      | Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                      | Phasellus nec iaculis mauris.
            .column.is-6
              .card.card-content
                .media
                  a
                    .media-content
                      p.title.is-4 Annual
                      p.subtitle.is-6 $190 per year 
                      .content
                        | Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                        | Phasellus nec iaculis mauris.

app/views/editor/page.html.slim
h1 Editor#page
p Find me in app/views/editor/page.html.slim

app/views/editor/show_setting.html.slim
h1 Editor#show_setting
p Find me in app/views/editor/show_setting.html.slim