config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  require 'sidekiq/web'
  ActiveAdmin.routes(self)

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  authenticate :user, ->(u) { u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end

  constraints(Subdomain.new) do
    match '/', to: 'site#home', via: [:get]
    get '/about', to: 'site#about'
    get '/news', to: 'site#news'
    get '/gallery', to: 'site#gallery'
    get '/events', to: 'site#events'
    get '/contact', to: 'site#contact'
    get '/gallery/:album_id', to: 'site#photo_albums', as: 'photo_albums'
    get '/terms_and_condition', to: 'site#terms_condition'
    get '/privacy_policy', to: 'site#privacy_policy'
  end

  resources :pages, except: %i[new edit]
  resources :fb_page, only: [:index] do
    resources :subscription, only: %i[new create]
    delete '/subscription/cancel', to: 'subscription#cancel_subscription', as: 'cancel_subscription'
    put 'sync', to: 'fb_page#sync', as: 'sync'
    get '/billing', to: 'billing#billing_history', as: 'billing_history'
  end
  mount StripeEvent::Engine, at: '/subscription/stripe/webhook'
  resources :fb_page_template, only: %i[show update]
  resources :billing, only: [:index]
  resources :dashboard, only: [:index]

  scope :editor do
    get 'design/:fb_page_id', to: 'editor#design', as: 'editor_design'
    get 'template/pages/:fb_page_id', to: 'editor#list_pages'
    put 'page/:fb_page_id', to: 'editor#page'
    post 'setting/:fb_page_id', to: 'editor#create_setting', as: 'editor_create_setting'
    get ':fb_page_id/setting/:fb_page_template_id', to: 'editor#show_setting', as: 'editor_show_setting'
  end

  scope :site do
    get ':fb_page_id/home', to: 'site#home', as: 'site_home'
    get ':fb_page_id/about', to: 'site#about', as: 'site_about'
    get ':fb_page_id/contact', to: 'site#contact', as: 'site_contact'
    post ':fb_page_id/contact', to: 'site#send_contact_message', as: 'site_contact_post'
    get ':fb_page_id/events', to: 'site#events', as: 'site_events'
    get ':fb_page_id/gallery', to: 'site#gallery', as: 'site_gallery'
    get ':fb_page_id/gallery/:album_id', to: 'site#photo_albums', as: 'site_photo_albums'
    get ':fb_page_id/privacy_policy', to: 'site#privacy_policy', as: 'site_privacy_policy'
    get ':fb_page_id/terms_condition', to: 'site#terms_condition', as: 'site_terms_condition'
    get ':fb_page_id/news', to: 'site#news', as: 'site_news'
  end

  put '/:fb_page_id/templates/:id/properties', to: 'templates#properties', as: 'properties'
  get '/:fb_page_id/templates', to: 'templates#index', as: 'templates'
  post '/:fb_page_id/templates/:template_id', to: 'templates#choose', as: 'choose_template'

  root to: 'home#index'
end

app/controllers/dashboard_controller.rb
# frozen_string_literal: true

class DashboardController < ApplicationController
  before_action :authenticate_user!

  def index
    @pages = DashboardDecorator.decorate_collection(current_user.fb_pages.order('fb_pages.status ASC, fb_pages.updated_at DESC'))
  end
end

app/views/shared/dashboard/_navbar.html.slim
nav.navbar.navbar-wrapper.is-solid.navbar-inverse.is-reverse
  .navbar-brand
    a.navbar-item href=(dashboard_index_url) 
      img alt="" src="https://bulkitv2.cssninja.io/agency/assets/images/logos/bulkit-white.svg"
    .custom-burger data-target="" 
      a.responsive-btn href="javascript:void(0);" 
        span.menu-toggle
          span.icon-box-toggle
            span.rotate
              i.icon-line-top
              i.icon-line-center
              i.icon-line-bottom
  .navbar-menu
    .navbar-start
    .navbar-end
      .navbar-item
        .mobile-drop.is-hidden-desktop.is-12
          = link_to root_path, { class: "mobile-menu parent-link #{controller.action_name == 'index' ? 'active' : ''}" } do
            i.sl.sl-icon-grid 
            | Dashboard
          = link_to root_path, { class: "mobile-menu parent-link #{controller.action_name == 'stats' ? 'active' : ''}" } do  
            i.sl.sl-icon-graph
            | Statistics
          = link_to root_path, { class: "mobile-menu parent-link #{controller.action_name == 'billing' ? 'active' : ''}" } do
            i.sl.sl-icon-briefcase
            | Billing
          = link_to root_path, { class: "mobile-menu parent-link #{controller.action_name == 'newsletter' ? 'active' : ''}" } do 
            i.sl.sl-icon-docs
            | Newsletter
          = link_to destroy_user_session_path, {class: "mobile-menu "} do
            i.sl.sl-icon-lock 
            | Logout
        - if current_user
          .navbar-item.has-dropdown.is-hoverable.is-hidden-mobile.is-hidden-tablet-only
            a.navbar-link href="javascript:void(0);" 
              = image_tag(current_user.image)
              | &nbsp
              = truncate current_user.name, length: 15
            .navbar-dropdown.is-boxed.is-medium
              = link_to destroy_user_session_path, {class: "navbar-item is-menu"} do
                | Logout

app/views/shared/dashboard/_sidebar.html.slim
nav.child-menu.is-sidebar-translated style="margin-top:74px; width:250px;"
  .child-menu-inner  
    ul#dashboard-menu.sidebar-menu.is-active.animated
      li.have-children
        = link_to dashboard_index_path, { class: "parent-link #{controller_name == 'dashboard' ? 'active' : ''}" } do
          i.fa.fa-th-large 
          | Dashboard
      li.have-children
        = link_to root_path, { class: "parent-link #{controller_name == 'stats' ? 'active' : ''}" } do 
          i.fa.fa-line-chart 
          | Statistics
      li.have-children
        = link_to billing_index_path, { class: "parent-link #{controller_name == 'billing' ? 'active' : ''}" } do
          i.fa.fa-money 
          | Billing
      / li.have-children
      /   = link_to root_path, { class: "parent-link #{controller.action_name == 'newsletter' ? 'active' : ''}" } do
      /     i.fa.fa-newspaper-o 
      /     | Newsletter